### ISSUE TITLE
Spellchecker freezes editor when file is opened

### ISSUE THREAD

**Issue by Typz** [CJCombrink/SpellChecker-Plugin#43]
When opening a large file (2600-lines c++ file) with spellchecker plugin enabled, the editor is not responsive for a few seconds (maybe 2 or 3). The problem does not happen when the plugin is disabled, with the same build of QtC on the same machine.

The same thing happens when the file is edited. This makes the plugin impossible to use whenever some slightly larger files are used.

Spellchecking should be done in the background, ensuring the interface (and especially editing) is not affected. It is perfectly fine to have a slight delay before the errors are displayed, like it is done with syntax/semantic hightlighting and code issues.

**Comment by CJCombrink** [comment]
Hi Typz,

I have pushed an update to attempt to do the spell checking in the background using QtConcurrent. 

Unfortunately I still have to extract the words in the same thread as the document updating process because it seems like the translation unit that I use to extract the comments, words and their positions from, gets invalidated directly after the update. 

Are you in a position to build the plugin and test? If not can you let me know what environment you are using, perhaps I can build something for you to test with (if Windows or Linux, but will only happen next week). 

There is still a crash that I have but do not have time to follow up on now, if one closes QtCreator when spell checking is in progress. For this reason I do not want to create an 'official' release. Finding the bug is difficult due to [build issues](https://bugreports.qt.io/browse/QTCREATORBUG-14917) that I have in Windows  but will look at this next week in Linux.

**Comment by Typz** [comment]
Hello,

I am a bit busy, but I will try to find time to build and try this.
I just had a quick look at the code, and I have a few comments:
* All connections to watcher must be made before actually creating/running
the watcher. (you connect to 'finished' after running the computation)
* The 'result' of the future is always in the main thread, so I don't think
you need a
* I don't really see the point in having multiple future watchers: can we
really call spellcheckWordsFromParser() multiple times in parallel? Having
the same watcher and just 'resetting' the future will somewhat cancel the
future...
* Running with QtConcurrent::Run() is easy, but does not allow to interrupt
the computation on cancel(), or to report partial results... A more generic
(but a bit more complicated and not documented) is to inherit from
QFutureInterface<WordList> and QRunnable: then instead of calling
QtConcurrent::Run() you create a new object of that class, and run it in
the threadpool (QThreadPool::globalInstance()->start()) and use the future
returned by QFutureInterface::future(). Not so complicated in fact, and you
can see exemple in QtCreator code, e.g. in plugins/cpptools/cppchecksymbol.*

I'll try the changes ASAP, keep in touch.
Best regards,

-- 
Francois

**Comment by CJCombrink** [comment]
Francois,

*>>All connections to watcher must be made before actually creating/running the watcher.*
Thanks, I understand why this can become an issue and have updated it accordingly. 

*>> The 'result' of the future is always in the main thread, so I don't think you need a mutex*
I was also thinking this, and removed it, but while searching for the last bug and crash I readded it again... 

*>> I don't really see the point in having multiple future watchers: can we really call spellcheckWordsFromParser() multiple times in parallel?*
Yes this can happen, I initially also though one would be fine until I started debugging. The C++ document parsers can run in parallel on different documents, thus the spell checker will run in parallel. This is useful if all files in the project must be parsed especially if they happen in parallel.

*>> Running with QtConcurrent::Run() is easy, but does not allow to interrupt
the computation on cancel(), or to report partial results...*
I am using the mechanisms as used in other places in the QtC code. It uses the QFutureInterface and an interesting runextensions.h file from <utils/QtConcurrentTools> to achieve this without deriving from QFutureInterface. The initial commit did not make use of the cancel functionality but the latest commit does implement this. 

Thank you very much for the help so far. 

Regards

**Comment by Typz** [comment]
Hello,

ok, good to see you are making progress.
I have quickly tried the new version today, and it still freezes for a second or two when opening a "large" file (between 2000 and 4000 lines I think)...

So seems to be a problem still... Maybe the word "analysis" (split/filter/... before running the actual spellchecker) should be done asynchronously as well, or/and maybe there is some direct signal connection somewhere or incorrect qobject "thread affinity"...

Thanks,

-- 
Francois

**Comment by CJCombrink** [comment]
Hi Francois,


> I have quickly tried the new version today, and it still freezes for a
> second or two when opening a "large" file (between 2000 and 4000 lines I
> think)...
>
I think I should get such a file, I will see what I can do in this regard.
How does the performance compare when editing the file (after it was
opened)?


So seems to be a problem still... Maybe the word "analysis"
> (split/filter/... before running the actual spellchecker) should be done
> asynchronously as well
>

As mentioned in one of my commit messages, the translation unit I use to
extract the comments get deleted as soon as the C++ parser completes the
parsing. For that reason I must use a direct connection connected to
the CppTools::CppModelManager on the documentUpdated() signal. I am not
sure of a way to either keep the translation unit alive or to make a copy
of it.

Regards,

**Comment by Typz** [comment]
In that case, you may indeed need the a direct connection, so you can "get" the translation unit. But:
- I think model manager is not in UI thread? it may help moving your receiving object to another thread, to avoid blocking the UI. That would still cause delay in the syntax coloration rendering, though
- translation unit (or document) is stored through a shared pointer: you may simply copy the shared pointer from your slot, then complete processing asynchronously
- it may be enough to extract de comments synchronously, but move all the regexp code for filtering/splitting words to make that part (which does not depend on translation unit!) asynchronous

Best regards,

-- 
Francois

**Comment by Typz** [comment]
Also, it seems strange this would be so heavy on the UI: scanning for
'words' is basically the same as highlighting the code, should not be so
slow...

So i had a better look at the code, and here are a few thoughts:
- Scanning for words is done by recursively checking each scope. Using some
visitor class would be cleaner, and maybe faster (?) but would a simple
lexing not be enough? Just running the Lexer to match words would
completely avoid this, since no preprocessor would be involved and thus the
matching would be immediate...
- Sorting and removing duplicates in the word list is done at each
iteration, certainly adds up; could be much faster to use a QSet to store
the words
- It may also be faster to push each 'word' to the background thread than
building a "large" list first: you would avoid allocations and
re-allocations
- Calls to translation unit to find the location is done after splitting
the words: e.g. will often happen multiple times for the same identifier.
Maybe it could be done once before splitting, which may improve perf and
allow to move more processing to background thread...

I'll try to see if using a QSet helps (seems like an easy thing to test),
let me know if there is something I can do to help you.

Best regards,

-- 
Francois

**Comment by CJCombrink** [comment]
@Typz 
I have just made a new release with some more optimistations regarding the parsing. 

I have not looked at moving the extraction of words from tokens to a separate thread but I have started thinking about it. it will require some rework, but there are a few benefits of doing it that way that I will explore in future.

The latest optimisation should add a bit of memory usage but hopefully improve performance when editing a file, opening and switching files can still be an issue. 

Regards,

**Comment by CJCombrink** [comment]
@Typz I have made a lot of changes in version 2.0.0 if you can perhaps test.

For now I am closing this issue since I feel confident that I have at least considered each point that you have raised with the latest release. Any feedback and suggestions are still welcome.
